name: Build and publish a Docker image
on:
    workflow_dispatch:
      inputs:
        version:
          type: choice
          options:
            - PATCH
            - MINOR
            - MAJOR
          

jobs:
    docker-build-push:
        name: Build & push docker image
        runs-on: ubuntu-latest
        env:
           IMG_NAME: ajzodak/flaskwebapp2024
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: 'Get Previous tag'
            id: previoustag
            uses: "WyriHaximus/github-action-get-previous-tag@v1"
            env:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              
          - name: 'Get next minor version'
            id: semvers
            uses: "WyriHaximus/github-action-next-semvers@v1"
            with:
              version: ${{ steps.previoustag.outputs.tag }}

          - name: Create release Patch
            if: ${{ inputs.version == 'PATCH' }}
            id: create_release_patch
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.semvers.outputs.patch }}
              release_name: Release ${{ steps.semvers.outputs.patch }}

          - name: Create release Minor
            if: ${{ inputs.version == 'MINOR' }}
            id: create_release_minor
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.semvers.outputs.minor }}
              release_name: Release ${{ steps.semvers.outputs.patch }}

          - name: Create release Major
            if: ${{ inputs.version == 'MAJOR' }}
            id: create_release_major
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.semvers.outputs.major }}
              release_name: Release ${{ steps.semvers.outputs.patch }}

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}


          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.semvers.outputs.patch }}